import Head from 'next/head'
import Image from 'next/image'
import { Popover, Transition } from '@headlessui/react'

import styles from '../styles/Home.module.css'
import Nav from './components/Nav'
import Hero from './components/Hero'
import Logos from './components/Logos'
import About from './components/About'

import ServicesTwo from './components/ServicesTwo'
import HeroCta from './components/HeroCta'
import Footer from './components/Footer'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Kickbord | Digital Marketing Agency</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="facebook-domain-verification" content="24lcp392vv2qjzg4jh17007pneerm2" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />

      </Head>
     
        <Nav /> 
        <Hero />
        
        <About />
        <Logos />
        <ServicesTwo />
        <HeroCta />
        <Footer />
     
     

  
    </div>
  )
}
