import type { Metadata } from 'next'
import Header from '@/components/header'
import FooterSection from '@/components/footer'

export const metadata: Metadata = {
    title: 'Tailark Quartz pages',
    description: 'Generated by create next app',
}

export default function MarketingLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <>
            <Header />
            <main
                role="main"
                className="bg-muted [--color-primary:var(--color-indigo-500)]">
                {children}
            </main>
            <FooterSection />
        </>
    )
}